Fix - Provide backward compatibility to remove event subscription
auth0/react-native-auth0 pull request #443
Opened 2022-01-05 16:08 UTC by poovamraj

### Changes

Please describe both what is changing and why this is important. Include:

- We have added a null check to ensure if old versions of RN uses our library (which is incompatible) we still provide compatibility in removing the event listener

### Testing

Manually tested for older versions of RN just to be sure. The recent versions can be tested using the unit test

- [x] This change adds unit test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] All existing and new tests complete without errors
- [x] All active GitHub checks have passed

2022-01-05 18:02 UTC, stevehobbsdev requested changes

2022-01-05 18:02 UTC, stevehobbsdev commented on src/webauth/agent.js
> +      const removeListner = () => {
Should this be `removeListener`? (Typo)

2022-01-06 09:22 UTC, poovamraj commented on src/webauth/agent.js
> +      const removeListner = () => {
I missed that. I have fixed this now

2022-01-06 11:56 UTC, Widcket approved these changes

2022-01-07 10:10 UTC, stevehobbsdev approved these changes

2022-01-07 10:53 UTC, merged