Add support for SMS passwordless login in useAuth0 hook
auth0/react-native-auth0 pull request #579
Opened 2022-12-27 20:46 UTC by sqiou11

### Changes

Add functions to the hook that initiate and complete the passwordless login process with SMS. Specifically:
- `sendSMSCode` - uses `Auth.passwordlessWithSMS` to send a code
- `loginWithSMS` - uses `Auth.authorizeWithSMS` to login using previously sent code, other than different input parameters its intended to function just like `authorize`.

This change is inspired by my own use-case in a project, where I originally duplicated some of the source code here and modified it locally, but I figured it could be useful to others as well. I'm quite new to React so happy to hear any feedback!

### Testing

Unit tests are added to test these two functions in use-auth0.spec.js. Since `loginWithSMS` is meant to behave just like `authorize` I've simply duplicated some of the test cases for that function. In the future some refactoring can be done to modularize the "scope" params processing into a shared utility, as it's now duplicated in both login methods and much of the unit test duplication is around this particular bit of logic.

- [x] This change adds unit test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] All existing and new tests complete without errors
- [x] All active GitHub checks have passed

2023-01-30 04:54 UTC, poovamraj commented
@sqiou11 this is a great PR indeed, but adding such methods to hooks would mean we would expose all the different kinds of authorization which is a lot and might bloat the API. that is why we were thinking to keep it to a minimum with the hooks and use the `auth0` object if more customization is required.

However I would like to keep this PR open to see if the community finds it as a requirement. 

Thank you for contributing to our repo :)

2023-02-01 17:02 UTC, tonydaly commented
We're trying to do the same flow and this PR would definitely be useful.

@poovamraj if this PR isn't merged what's the best way to achieve the same result with the current hooks?

I've setup my `Auth0Provider`, but once I've done `auth0.auth.loginWithSMS` and `auth0.credentialsManager.saveCredentials` the hooks don't automatically update? However, once I do a refresh then everything works.

I've had to create a new Auth0 client to call these methods as they don't seem to be exposed by `useAuth0`.

Any help appreciated!

2023-02-01 21:51 UTC, sqiou11 commented
Thanks @poovamraj for the reply! Totally understand the API concerns. Would a separate hook+context+provider dedicated to passwordless authentication be better? That's essentially what I've done in my project so if that's the intention in this library and what you meant when you said "use the `auth0` object if more customization is required" then good to know :).

@tonydaly not sure what you mean by "setup my `Auth0Provider` but I don't think using the existing provider and then additionally creating a new Auth0 client to use `loginWithSMS` will work. The existing `Auth0Provider` creates it's own Auth0 client underneath, plus your new Auth0 client isn't tied to the existing `Auth0Provider`'s state. What I did was define my own version of everything - `Auth0Provider`, `Auth0Context`, and `useAuth0`.

2023-02-02 06:45 UTC, poovamraj commented
@sqiou11 A seperate hook for all the Authentication APIs is definitely one we are considering, but we are still worried about the following concerns
- Would we have common state like `user` `error` `isInitilaized` in this hook as well?
- If we want the user to use these from the older `useAuth0` hook, then will it be confusing to call a method from one hook and expect the error in other hook
- Is it better to avoid all these confusions and just add all the authentication APIs to the current hook itself.

I'd love to hear everyone's thoughts on this as well.

2023-02-02 06:47 UTC, poovamraj commented
@tonydaly as @sqiou11 suggested at this point the library doesn't support hooks with Authentication APIs. You have to setup the flow yourself.

We came to this conclusion considering projects which does embedded login would be complex enough that they would like to manage their own states. But looks like this would be a good addition to our Hooks API. We would like to consider how we want to design this API before starting on it!

2023-02-06 03:42 UTC, poovamraj commented
Hi @sqiou11, we would like to introduce all our APIs through the single hook. Will it be possible for you to update the PR with all the other authentication endpoints as well?

2023-02-06 18:54 UTC, sqiou11 commented
> 

That's great to hear! I will work on updating the PR accordingly.

2023-02-07 13:48 UTC, poovamraj commented
Thanks a lot @sqiou11 thats great of you 🙏

2023-03-31 14:22 UTC, poovamraj commented
Hi @sqiou11 I see that you have done some amazing work in the PR. You think it is ready for review now?

2023-03-31 15:56 UTC, sqiou11 commented
> Hi @sqiou11 I see that you have done some amazing work in the PR. You think it is ready for review now?

Yep! It’s ready for review

2023-04-05 17:17 UTC, poovamraj requested changes
This is great work! I have added few NITs to the review. 

The name change to the methods are great. It is better than the previous naming we have used. Since we won't be able to change the naming once we release this, I wanted to check with the team internally as well to have more eyes on this before we go ahead. Will keep you in the loop about this though.

Thanks again for this amazing PR!

2023-04-08 13:58 UTC, sqiou11 commented on src/hooks/auth0-provider.js
> +        console.log(error);
Removed

2023-04-08 13:59 UTC, sqiou11 commented on src/hooks/auth0-provider.js
> +        console.log(error);
Should be cleaned up now

2023-04-08 14:03 UTC, sqiou11 commented
Sounds good!

2023-04-12 18:58 UTC, evansims commented
(Just giving the CI a kick to resolve some stalled tests.)

2023-05-02 10:51 UTC, andrewflo commented
Would love to see this change :) Great work and looking forward to seeing if this one gets merged!

2023-05-17 15:43 UTC, poovamraj commented
@SafiUllahAshfaq This is a valid feedback. We will explore supporting this and keep you updated

@andrewflo We are actively looking into this feature and we should be merging it as part of our next major version of this SDK.

2023-05-28 14:37 UTC, sqiou11 commented
@poovamraj since it's my first time creating a PR for a repo that isn't mine, just want to make sure that I'm doing things correctly here. I resolved your comments earlier with the extraneous log statements. Is there something else on my end that you're waiting on?

2023-05-29 15:25 UTC, poovamraj commented
Hi @sqiou11, this is a great contribution to our project and we are really sorry this is taking a long time to get merged. The plan is to merge it along with our v3 release. We have plans to pick this PR up again in the coming weeks. Again, sorry for the delay. This is some great work here. Thank you 🙏

2023-06-01 01:24 UTC, sqiou11 commented
> Hi @sqiou11, this is a great contribution to our project and we are really sorry this is taking a long time to get merged. The plan is to merge it along with our v3 release. We have plans to pick this PR up again in the coming weeks. Again, sorry for the delay. This is some great work here. Thank you 🙏

No problem! Take all the time you need, just wanted to make sure I wasn't blocking you all.

2023-06-05 16:16 UTC, frederikprijck submitted a review, later dismissed

2023-06-05 16:18 UTC, merged

2023-06-05 16:19 UTC, poovamraj commented
Thanks a lot @sqiou11! Without you this wouldn't have been possible 👍 🙇 We really appreciate your contribution to our repo!